version: '3'

tasks:
  default:
    cmds:
      - task --list

  install:
    desc: Install project dependencies
    cmds:
      - npm install

  dev:
    desc: Start development server
    cmds:
      - npm run dev

  build:
    desc: Build the project
    cmds:
      - npm run build

  test:
    desc: Run tests
    cmds:
      - npm test

  lint:
    desc: Run linter
    cmds:
      - npm run lint

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf dist
      - rm -rf node_modules
      - rm -rf .next

  format:
    desc: Format code
    cmds:
      - npm run format 