version: '3'
output: 'prefixed'

vars:
  VERSION:
    sh: git describe --tags --always --dirty
  BUILD_TIME:
    sh: date -u '+%Y-%m-%d_%H:%M:%S'
  GIT_COMMIT:
    sh: git rev-parse HEAD
  GO_VERSION:
    sh: go version | cut -d ' ' -f 3
  LDFLAGS: -s -w -X main.version={{.VERSION}} -X main.buildTime={{.BUILD_TIME}} -X main.gitCommit={{.GIT_COMMIT}} -X main.goVersion={{.GO_VERSION}}
  WEBVIEW_FLAGS: -ldflags "-H windowsgui" # For Windows
  # WEBVIEW_FLAGS: -ldflags "-s -w" # For Linux/Mac

tasks:
  default:
    cmds:
      - task: install
      - task: build
      - task: run

  install:
    desc: Install project dependencies
    cmds:
      - go mod tidy
      - go install github.com/gorilla/mux@latest
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install github.com/webview/webview@latest
      - export PATH=$PATH:$(go env GOPATH)/bin

  build:
    desc: Build the application
    deps: [lint]
    cmds:
      - go build {{.WEBVIEW_FLAGS}} -o bin/server main.go

  run:
    desc: Run the application
    cmds:
      - ./bin/server

  dev:
    desc: Run development environment
    cmds:
      - go run main.go

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/ uploads/

  lint:
    desc: Run all linters
    deps: [lint:backend, lint:frontend]

  lint:backend:
    desc: Run linters for Go code
    cmds:
      - go fmt ./...
      - go vet ./...
      - golangci-lint run ./...

  lint:frontend:
    desc: Run linters for frontend code
    cmds:
      - echo "Frontend linting not configured yet"

  lint:fix:
    desc: Fix all linting issues
    deps: [lint:fix:backend, lint:fix:frontend]

  lint:fix:backend:
    desc: Fix linting issues in Go code
    cmds:
      - go fmt ./...

  lint:fix:frontend:
    desc: Fix linting issues in frontend code
    cmds:
      - echo "Frontend lint fixing not configured yet"

  test:
    desc: Run all tests
    cmds:
      - go test -v -race -coverprofile=coverage.out -covermode=atomic ./...
      - go tool cover -html=coverage.out -o coverage.html 