version: '3'

# Global variables
vars:
  # Version information
  VERSION:
    sh: git describe --tags --always --dirty
  BUILD_TIME:
    sh: powershell -Command "Get-Date -Format 'yyyy-MM-dd_HH:mm:ss'"
  GIT_COMMIT:
    sh: git rev-parse HEAD
  GO_VERSION:
    sh: powershell -Command "(go version).Split(' ')[2]"

  # Build configuration
  BIN_DIR: bin
  FRONTEND_DIR: webview
  UPLOAD_DIR: uploads
  MAIN_PACKAGE: main.go
  DIST_DIR: static/dist

  # Build flags
  LDFLAGS: >-
    -s -w -X main.version={{.VERSION}} -X main.buildTime={{.BUILD_TIME}} -X main.gitCommit={{.GIT_COMMIT}} -X main.goVersion={{.GO_VERSION}}

# Global settings
output: prefixed
silent: false

# Include platform-specific tasks
includes:
  windows: Taskfile.windows.yml
  # linux: Taskfile.linux.yml
  # darwin: Taskfile.darwin.yml

tasks:
  default:
    desc: Default task - installs dependencies, builds and runs the application
    cmds:
    - task build
    - task run

  deps:
    desc: Install all dependencies
    deps: [ deps:go, deps:frontend ]

  deps:go:
    desc: Install Go dependencies
    cmds:
    - go mod download
    - go mod tidy

  deps:frontend:
    desc: Install frontend dependencies
    dir: "{{.FRONTEND_DIR}}"
    cmds:
    - npm install --legacy-peer-deps

  build:
    desc: Build the application
    deps: [ validate, build:frontend ]
    cmds:
    - go build -ldflags "{{.LDFLAGS}}" -o {{.BIN_DIR}}/server {{.MAIN_PACKAGE}}

  build:frontend:
    desc: Build frontend assets
    dir: "{{.FRONTEND_DIR}}"
    cmds:
    - npm run build

  run:
    desc: Run the application
    cmds:
    - ./bin/server

  dev:
    desc: Run development environment
    deps: [ dev:backend, dev:frontend ]

  dev:backend:
    desc: Run backend in development mode
    cmds:
    - go run {{.MAIN_PACKAGE}}

  dev:frontend:
    desc: Run frontend development server
    dir: "{{.FRONTEND_DIR}}"
    cmds:
    - npm run dev

  watch:
    desc: Watch for changes and rebuild
    cmds:
    - task: dev
      ignore_error: true
    - task: build
      ignore_error: true

  clean:
    desc: Clean build artifacts and temporary files
    cmds:
    - powershell -Command "if (Test-Path {{.BIN_DIR}}) { Remove-Item -Recurse -Force {{.BIN_DIR}} }"
    - powershell -Command "if (Test-Path {{.UPLOAD_DIR}}) { Remove-Item -Recurse -Force {{.UPLOAD_DIR}} }"
    - powershell -Command "if (Test-Path {{.DIST_DIR}}) { Remove-Item -Recurse -Force {{.DIST_DIR}} }"
    - powershell -Command "if (Test-Path coverage.out) { Remove-Item -Force coverage.out }"
    - powershell -Command "if (Test-Path coverage.html) { Remove-Item -Force coverage.html }"
    - powershell -Command "if (Test-Path {{.FRONTEND_DIR}}/node_modules) { Remove-Item -Recurse -Force {{.FRONTEND_DIR}}/node_modules }"
    - powershell -Command "if (Test-Path {{.FRONTEND_DIR}}/dist) { Remove-Item -Recurse -Force {{.FRONTEND_DIR}}/dist }"
    - go clean -cache -testcache

  validate:
    desc: Run all validation checks
    deps: [ lint, test, typecheck ]

  lint:
    desc: Run all linters
    deps: [ lint:backend, lint:frontend ]

  lint:backend:
    desc: Run linters for Go code
    cmds:
    - go fmt ./...
    - go vet ./...
    - golangci-lint run ./...

  lint:frontend:
    desc: Run linters for frontend code
    dir: "{{.FRONTEND_DIR}}"
    cmds:
    - npm run lint

  lint:fix:
    desc: Fix all linting issues
    deps: [ lint:fix:backend, lint:fix:frontend ]

  lint:fix:backend:
    desc: Fix linting issues in Go code
    cmds:
    - go fmt ./...

  lint:fix:frontend:
    desc: Fix linting issues in frontend code
    dir: "{{.FRONTEND_DIR}}"
    cmds:
    - npm run lint:fix

  test:
    desc: Run all tests
    cmds:
    - go test -v -race ./...

  test:coverage:
    desc: Run tests with coverage report
    cmds:
    - go test -v -race -coverprofile=coverage.out -covermode=atomic ./...
    - go tool cover -html=coverage.out -o coverage.html

  typecheck:
    desc: Run TypeScript type checking
    dir: "{{.FRONTEND_DIR}}"
    cmds:
    - npm run typecheck

  setup:
    desc: Initial project setup
    cmds:
    - task deps
    - task build
    - task validate
