name: Deploy to GitHub Pages

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
    types: [ opened, synchronize ]
  workflow_dispatch:


concurrency:
  group: 'pages'
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: read
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: true

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.2'
        cache: true

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install Go dependencies
      run: go mod download

    - name: Run Go tests
      run: go test ./...

    - name: Install frontend dependencies
      run: npm ci

    - name: Run frontend tests
      run: npm run test:unit:run

  build:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: read
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.2'
        cache: true

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install Go dependencies
      run: go mod download

    - name: Build Go application
      run: go build -o kiosk-video-recorder

    - name: Install frontend dependencies
      run: npm ci

    - name: Build frontend
      env:
        BASE_PATH: '/${{ github.event.repository.name }}'
        NODE_ENV: production
      run: npm run build

    - name: Upload Pages artifact
      if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main' && !env.ACT
      uses: actions/upload-pages-artifact@v3
      with:
        path: webview/dist/
        retention-days: 30

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
      contents: read
      pull-requests: read
    steps:
    - name: Deploy to GitHub Pages
      if: ${{ !env.ACT }}
      id: deployment
      uses: actions/deploy-pages@v4
